{$phpUse}

{$ajaxBlockStart}

<!DOCTYPE html>
<html>
<head>
<meta charset="{$charset}">
<title>{$title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{$keywords}

{$description}

{$customHead}

<link type="text/css" rel="stylesheet" href="{$siteStaticBaseUrl}/bootstrap/3.0.0/css/bootstrap.min.css" media="all">
<link type="text/css" rel="stylesheet" href="{$siteStaticBaseUrl}/{=strtolower($appName)}/css/style.css" media="all"/>
{$pageStyle}

<script type="text/javascript" src="{$siteStaticBaseUrl}/js/jquery.min.js"></script>
<script type="text/javascript" src="{$siteStaticBaseUrl}/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{$siteStaticBaseUrl}/{=strtolower($appName)}/js/app.js"></script>
{$pageScript}

{$customScript}

{$customStyle}

</head>
{$customBody}


<div id="header" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" target="_top">{$appName}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</div>

{$ajaxBlockEnd}