namespace Apps\Shared\Helper;

use System\Core\App, System\Core\Request;
use Apps\Shared, Apps\{$isSharedController?'Shared':$appName}\Model;

//use System\Util;
//use System\Core\stdModel;

/**
 * Class AppHelper
 * @package Apps\Shared\Helper
 */
class AppHelper
{

    // ----------------------  public static methods  ----------------------


    // ----------------------  private static methods  ----------------------

}